'''Código feito somente para formatar os links da categorias e a quantidade de páginas em um csv'''

import pandas as pd

texto = """
https://www.spreadthesign.com/pt.br/search/by-category/398/lingua-de-sinais-para-iniciantes/ 6
https://www.spreadthesign.com/pt.br/search/by-category/1/diversos/ 23
https://www.spreadthesign.com/pt.br/search/by-category/2/cores/ 1
https://www.spreadthesign.com/pt.br/search/by-category/8/medidas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/11/emocoes/ 6
https://www.spreadthesign.com/pt.br/search/by-category/12/caracteristicas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/3/numeros/ 6
https://www.spreadthesign.com/pt.br/search/by-category/6/geral-tempo/ 4
https://www.spreadthesign.com/pt.br/search/by-category/2/cores/ 1
https://www.spreadthesign.com/pt.br/search/by-category/8/medidas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/11/emocoes/ 6
https://www.spreadthesign.com/pt.br/search/by-category/12/caracteristicas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/3/numeros/ 6
https://www.spreadthesign.com/pt.br/search/by-category/6/geral-tempo/ 4
https://www.spreadthesign.com/pt.br/search/by-category/37/frases/ 2
https://www.spreadthesign.com/pt.br/search/by-category/36/saudacoes-e-frases-padrao/ 1
https://www.spreadthesign.com/pt.br/search/by-category/38/questoes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/397/expressao-idiomaticas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/36/saudacoes-e-frases-padrao/ 1
https://www.spreadthesign.com/pt.br/search/by-category/38/questoes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/397/expressao-idiomaticas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/86/religiao/ 9
https://www.spreadthesign.com/pt.br/search/by-category/98/magia-e-mistica/ 2
https://www.spreadthesign.com/pt.br/search/by-category/97/pecados-atitudes-e-emocoes-negativas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/88/estudos-teologicos/ 6
https://www.spreadthesign.com/pt.br/search/by-category/91/artefatos-e-simbolos/ 1
https://www.spreadthesign.com/pt.br/search/by-category/98/magia-e-mistica/ 2
https://www.spreadthesign.com/pt.br/search/by-category/97/pecados-atitudes-e-emocoes-negativas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/88/estudos-teologicos/ 6
https://www.spreadthesign.com/pt.br/search/by-category/91/artefatos-e-simbolos/ 1
https://www.spreadthesign.com/pt.br/search/by-category/13/pedagogia/ 15
https://www.spreadthesign.com/pt.br/search/by-category/17/graus-e-certificacoes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/26/cuidados-infantis/ 1
https://www.spreadthesign.com/pt.br/search/by-category/15/educacao-e-aprendizagem/ 13
https://www.spreadthesign.com/pt.br/search/by-category/17/graus-e-certificacoes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/26/cuidados-infantis/ 1
https://www.spreadthesign.com/pt.br/search/by-category/15/educacao-e-aprendizagem/ 13
https://www.spreadthesign.com/pt.br/search/by-category/28/lingua/ 62
https://www.spreadthesign.com/pt.br/search/by-category/29/diferentes-linguas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/35/fala/ 2
https://www.spreadthesign.com/pt.br/search/by-category/30/gramatica-e-termos/ 5
https://www.spreadthesign.com/pt.br/search/by-category/32/lingua-de-sinais/ 2
https://www.spreadthesign.com/pt.br/search/by-category/40/verbos/ 17
https://www.spreadthesign.com/pt.br/search/by-category/39/adjetivos/ 11
https://www.spreadthesign.com/pt.br/search/by-category/42/preposicoes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/43/substantivos/ 20
https://www.spreadthesign.com/pt.br/search/by-category/41/adverbios/ 4
https://www.spreadthesign.com/pt.br/search/by-category/250/conjuncoes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/246/pronomes-e-titulos-honorificos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/31/profano-e-giria/ 2
https://www.spreadthesign.com/pt.br/search/by-category/29/diferentes-linguas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/35/fala/ 2
https://www.spreadthesign.com/pt.br/search/by-category/30/gramatica-e-termos/ 5
https://www.spreadthesign.com/pt.br/search/by-category/32/lingua-de-sinais/ 2
https://www.spreadthesign.com/pt.br/search/by-category/40/verbos/ 17
https://www.spreadthesign.com/pt.br/search/by-category/39/adjetivos/ 11
https://www.spreadthesign.com/pt.br/search/by-category/42/preposicoes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/43/substantivos/ 20
https://www.spreadthesign.com/pt.br/search/by-category/41/adverbios/ 4
https://www.spreadthesign.com/pt.br/search/by-category/250/conjuncoes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/246/pronomes-e-titulos-honorificos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/31/profano-e-giria/ 2
https://www.spreadthesign.com/pt.br/search/by-category/113/arte-e-entretenimento/ 28
https://www.spreadthesign.com/pt.br/search/by-category/118/musica/ 3
https://www.spreadthesign.com/pt.br/search/by-category/120/artes-cenicas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/119/filmes-e-televisao/ 4
https://www.spreadthesign.com/pt.br/search/by-category/121/literatura-e-texto/ 6
https://www.spreadthesign.com/pt.br/search/by-category/122/costura-e-material-de-costura/ 3
https://www.spreadthesign.com/pt.br/search/by-category/116/imagens/ 3
https://www.spreadthesign.com/pt.br/search/by-category/114/pintura-e-desenho/ 3
https://www.spreadthesign.com/pt.br/search/by-category/117/arquitetura/ 3
https://www.spreadthesign.com/pt.br/search/by-category/124/geral-arte/ 5
https://www.spreadthesign.com/pt.br/search/by-category/118/musica/ 3
https://www.spreadthesign.com/pt.br/search/by-category/120/artes-cenicas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/119/filmes-e-televisao/ 4
https://www.spreadthesign.com/pt.br/search/by-category/121/literatura-e-texto/ 6
https://www.spreadthesign.com/pt.br/search/by-category/122/costura-e-material-de-costura/ 3
https://www.spreadthesign.com/pt.br/search/by-category/116/imagens/ 3
https://www.spreadthesign.com/pt.br/search/by-category/114/pintura-e-desenho/ 3
https://www.spreadthesign.com/pt.br/search/by-category/117/arquitetura/ 3
https://www.spreadthesign.com/pt.br/search/by-category/124/geral-arte/ 5
https://www.spreadthesign.com/pt.br/search/by-category/46/estudos-sociais/ 55
https://www.spreadthesign.com/pt.br/search/by-category/48/leis-e-politicas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/47/politica/ 6
https://www.spreadthesign.com/pt.br/search/by-category/65/crime-e-punicao/ 4
https://www.spreadthesign.com/pt.br/search/by-category/57/servico-publico/ 3
https://www.spreadthesign.com/pt.br/search/by-category/49/economia/ 8
https://www.spreadthesign.com/pt.br/search/by-category/50/comercio/ 5
https://www.spreadthesign.com/pt.br/search/by-category/51/negocios/ 4
https://www.spreadthesign.com/pt.br/search/by-category/52/trabalho/ 9
https://www.spreadthesign.com/pt.br/search/by-category/56/profissoes/ 6
https://www.spreadthesign.com/pt.br/search/by-category/59/organizacoes-e-companhias-especializadas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/394/sociedade-surda/ 1
https://www.spreadthesign.com/pt.br/search/by-category/62/multimidia-e-informacao/ 3
https://www.spreadthesign.com/pt.br/search/by-category/252/humanos/ 4
https://www.spreadthesign.com/pt.br/search/by-category/66/historia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/67/militar-e-armamento/ 3
https://www.spreadthesign.com/pt.br/search/by-category/48/leis-e-politicas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/47/politica/ 6
https://www.spreadthesign.com/pt.br/search/by-category/65/crime-e-punicao/ 4
https://www.spreadthesign.com/pt.br/search/by-category/57/servico-publico/ 3
https://www.spreadthesign.com/pt.br/search/by-category/49/economia/ 8
https://www.spreadthesign.com/pt.br/search/by-category/50/comercio/ 5
https://www.spreadthesign.com/pt.br/search/by-category/51/negocios/ 4
https://www.spreadthesign.com/pt.br/search/by-category/52/trabalho/ 9
https://www.spreadthesign.com/pt.br/search/by-category/56/profissoes/ 6
https://www.spreadthesign.com/pt.br/search/by-category/59/organizacoes-e-companhias-especializadas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/394/sociedade-surda/ 1
https://www.spreadthesign.com/pt.br/search/by-category/62/multimidia-e-informacao/ 3
https://www.spreadthesign.com/pt.br/search/by-category/252/humanos/ 4
https://www.spreadthesign.com/pt.br/search/by-category/66/historia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/67/militar-e-armamento/ 3
https://www.spreadthesign.com/pt.br/search/by-category/99/geografia-e-viagens/ 18
https://www.spreadthesign.com/pt.br/search/by-category/402/capitals/ 3
https://www.spreadthesign.com/pt.br/search/by-category/283/africa/ 2
https://www.spreadthesign.com/pt.br/search/by-category/282/asia/ 2
https://www.spreadthesign.com/pt.br/search/by-category/284/australia-e-oceania/ 1
https://www.spreadthesign.com/pt.br/search/by-category/281/europa/ 3
https://www.spreadthesign.com/pt.br/search/by-category/280/america-do-norte/ 1
https://www.spreadthesign.com/pt.br/search/by-category/279/america-do-sul/ 1
https://www.spreadthesign.com/pt.br/search/by-category/108/atracoes-turisticas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/100/paises-e-continentes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/247/geral-viagens/ 6
https://www.spreadthesign.com/pt.br/search/by-category/103/geral-geografia/ 4
https://www.spreadthesign.com/pt.br/search/by-category/402/capitals/ 3
https://www.spreadthesign.com/pt.br/search/by-category/283/africa/ 2
https://www.spreadthesign.com/pt.br/search/by-category/282/asia/ 2
https://www.spreadthesign.com/pt.br/search/by-category/284/australia-e-oceania/ 1
https://www.spreadthesign.com/pt.br/search/by-category/281/europa/ 3
https://www.spreadthesign.com/pt.br/search/by-category/280/america-do-norte/ 1
https://www.spreadthesign.com/pt.br/search/by-category/279/america-do-sul/ 1
https://www.spreadthesign.com/pt.br/search/by-category/108/atracoes-turisticas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/100/paises-e-continentes/ 1
https://www.spreadthesign.com/pt.br/search/by-category/247/geral-viagens/ 6
https://www.spreadthesign.com/pt.br/search/by-category/103/geral-geografia/ 4
https://www.spreadthesign.com/pt.br/search/by-category/125/comida-e-bebidas/ 21
https://www.spreadthesign.com/pt.br/search/by-category/126/culinaria-e-panificacao/ 5
https://www.spreadthesign.com/pt.br/search/by-category/129/comer-e-beber/ 4
https://www.spreadthesign.com/pt.br/search/by-category/132/peixe-e-marisco/ 1
https://www.spreadthesign.com/pt.br/search/by-category/131/carne/ 1
https://www.spreadthesign.com/pt.br/search/by-category/134/vegetais/ 2
https://www.spreadthesign.com/pt.br/search/by-category/135/frutas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/139/especiarias-e-ervas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/136/sobremesas-e-doces/ 2
https://www.spreadthesign.com/pt.br/search/by-category/140/nozes-e-lanches/ 1
https://www.spreadthesign.com/pt.br/search/by-category/142/bebidas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/141/outras-comidas-e-ingredientes/ 3
https://www.spreadthesign.com/pt.br/search/by-category/130/pratos-especificos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/259/producao-e-venda-de-alimentos/ 1
https://www.spreadthesign.com/pt.br/search/by-category/126/culinaria-e-panificacao/ 5
https://www.spreadthesign.com/pt.br/search/by-category/129/comer-e-beber/ 4
https://www.spreadthesign.com/pt.br/search/by-category/132/peixe-e-marisco/ 1
https://www.spreadthesign.com/pt.br/search/by-category/131/carne/ 1
https://www.spreadthesign.com/pt.br/search/by-category/134/vegetais/ 2
https://www.spreadthesign.com/pt.br/search/by-category/135/frutas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/139/especiarias-e-ervas/ 1
https://www.spreadthesign.com/pt.br/search/by-category/136/sobremesas-e-doces/ 2
https://www.spreadthesign.com/pt.br/search/by-category/140/nozes-e-lanches/ 1
https://www.spreadthesign.com/pt.br/search/by-category/142/bebidas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/141/outras-comidas-e-ingredientes/ 3
https://www.spreadthesign.com/pt.br/search/by-category/130/pratos-especificos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/259/producao-e-venda-de-alimentos/ 1
https://www.spreadthesign.com/pt.br/search/by-category/68/estilo-de-vida/ 29
https://www.spreadthesign.com/pt.br/search/by-category/70/roupas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/71/joalharia-e-acessorios/ 2
https://www.spreadthesign.com/pt.br/search/by-category/76/beleza-e-cosmeticos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/74/cabelo/ 4
https://www.spreadthesign.com/pt.br/search/by-category/69/compras/ 2
https://www.spreadthesign.com/pt.br/search/by-category/78/diversao/ 2
https://www.spreadthesign.com/pt.br/search/by-category/84/celebracoes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/83/familia-e-relacoes/ 3
https://www.spreadthesign.com/pt.br/search/by-category/85/casamento-e-nupcias/ 1
https://www.spreadthesign.com/pt.br/search/by-category/396/sexo/ 1
https://www.spreadthesign.com/pt.br/search/by-category/77/bebes-e-criancas/ 3
https://www.spreadthesign.com/pt.br/search/by-category/80/mobilia/ 6
https://www.spreadthesign.com/pt.br/search/by-category/82/trabalho-domestico/ 3
https://www.spreadthesign.com/pt.br/search/by-category/70/roupas/ 4
https://www.spreadthesign.com/pt.br/search/by-category/71/joalharia-e-acessorios/ 2
https://www.spreadthesign.com/pt.br/search/by-category/76/beleza-e-cosmeticos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/74/cabelo/ 4
https://www.spreadthesign.com/pt.br/search/by-category/69/compras/ 2
https://www.spreadthesign.com/pt.br/search/by-category/78/diversao/ 2
https://www.spreadthesign.com/pt.br/search/by-category/84/celebracoes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/83/familia-e-relacoes/ 3
https://www.spreadthesign.com/pt.br/search/by-category/85/casamento-e-nupcias/ 1
https://www.spreadthesign.com/pt.br/search/by-category/396/sexo/ 1
https://www.spreadthesign.com/pt.br/search/by-category/77/bebes-e-criancas/ 3
https://www.spreadthesign.com/pt.br/search/by-category/80/mobilia/ 6
https://www.spreadthesign.com/pt.br/search/by-category/82/trabalho-domestico/ 3
https://www.spreadthesign.com/pt.br/search/by-category/147/esportes-e-lazer/ 20
https://www.spreadthesign.com/pt.br/search/by-category/151/esportes-de-raquete/ 1
https://www.spreadthesign.com/pt.br/search/by-category/148/futebol/ 2
https://www.spreadthesign.com/pt.br/search/by-category/149/atletismo/ 1
https://www.spreadthesign.com/pt.br/search/by-category/150/ginastica/ 1
https://www.spreadthesign.com/pt.br/search/by-category/152/natacao/ 2
https://www.spreadthesign.com/pt.br/search/by-category/401/poker/ 1
https://www.spreadthesign.com/pt.br/search/by-category/156/equitacao/ 1
https://www.spreadthesign.com/pt.br/search/by-category/153/esportes-de-combate/ 1
https://www.spreadthesign.com/pt.br/search/by-category/154/escalada/ 2
https://www.spreadthesign.com/pt.br/search/by-category/157/deportos-com-remo/ 1
https://www.spreadthesign.com/pt.br/search/by-category/158/outros-esportes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/160/equipamento/ 2
https://www.spreadthesign.com/pt.br/search/by-category/159/instalacoes-e-campos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/163/concorrentes-e-competicoes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/162/jogadas-e-estrategias/ 1
https://www.spreadthesign.com/pt.br/search/by-category/164/exercicio/ 2
https://www.spreadthesign.com/pt.br/search/by-category/165/jogos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/166/geral-exercicio/ 2
https://www.spreadthesign.com/pt.br/search/by-category/151/esportes-de-raquete/ 1
https://www.spreadthesign.com/pt.br/search/by-category/148/futebol/ 2
https://www.spreadthesign.com/pt.br/search/by-category/149/atletismo/ 1
https://www.spreadthesign.com/pt.br/search/by-category/150/ginastica/ 1
https://www.spreadthesign.com/pt.br/search/by-category/152/natacao/ 2
https://www.spreadthesign.com/pt.br/search/by-category/401/poker/ 1
https://www.spreadthesign.com/pt.br/search/by-category/156/equitacao/ 1
https://www.spreadthesign.com/pt.br/search/by-category/153/esportes-de-combate/ 1
https://www.spreadthesign.com/pt.br/search/by-category/154/escalada/ 2
https://www.spreadthesign.com/pt.br/search/by-category/157/deportos-com-remo/ 1
https://www.spreadthesign.com/pt.br/search/by-category/158/outros-esportes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/160/equipamento/ 2
https://www.spreadthesign.com/pt.br/search/by-category/159/instalacoes-e-campos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/163/concorrentes-e-competicoes/ 2
https://www.spreadthesign.com/pt.br/search/by-category/162/jogadas-e-estrategias/ 1
https://www.spreadthesign.com/pt.br/search/by-category/164/exercicio/ 2
https://www.spreadthesign.com/pt.br/search/by-category/165/jogos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/166/geral-exercicio/ 2
https://www.spreadthesign.com/pt.br/search/by-category/213/tecnologia/ 39
https://www.spreadthesign.com/pt.br/search/by-category/221/construcao/ 6
https://www.spreadthesign.com/pt.br/search/by-category/224/ferramentas/ 6
https://www.spreadthesign.com/pt.br/search/by-category/225/maquinaria/ 3
https://www.spreadthesign.com/pt.br/search/by-category/223/trabalhos-em-metal/ 2
https://www.spreadthesign.com/pt.br/search/by-category/220/tecnologia-de-veiculos/ 8
https://www.spreadthesign.com/pt.br/search/by-category/219/carros-e-veiculos-especificos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/214/eletricidade/ 5
https://www.spreadthesign.com/pt.br/search/by-category/216/som-luz/ 2
https://www.spreadthesign.com/pt.br/search/by-category/112/geral-viagens/ 4
https://www.spreadthesign.com/pt.br/search/by-category/215/ar-e-forca-hidraulica/ 2
https://www.spreadthesign.com/pt.br/search/by-category/226/geral-tecnologia/ 4
https://www.spreadthesign.com/pt.br/search/by-category/221/construcao/ 6
https://www.spreadthesign.com/pt.br/search/by-category/224/ferramentas/ 6
https://www.spreadthesign.com/pt.br/search/by-category/225/maquinaria/ 3
https://www.spreadthesign.com/pt.br/search/by-category/223/trabalhos-em-metal/ 2
https://www.spreadthesign.com/pt.br/search/by-category/220/tecnologia-de-veiculos/ 8
https://www.spreadthesign.com/pt.br/search/by-category/219/carros-e-veiculos-especificos/ 2
https://www.spreadthesign.com/pt.br/search/by-category/214/eletricidade/ 5
https://www.spreadthesign.com/pt.br/search/by-category/216/som-luz/ 2
https://www.spreadthesign.com/pt.br/search/by-category/112/geral-viagens/ 4
https://www.spreadthesign.com/pt.br/search/by-category/215/ar-e-forca-hidraulica/ 2
https://www.spreadthesign.com/pt.br/search/by-category/226/geral-tecnologia/ 4
https://www.spreadthesign.com/pt.br/search/by-category/227/computadores-e-tecnologia-moderna/ 15
https://www.spreadthesign.com/pt.br/search/by-category/228/tecnologia-de-computadores/ 7
https://www.spreadthesign.com/pt.br/search/by-category/234/comunicacao-telefones/ 1
https://www.spreadthesign.com/pt.br/search/by-category/233/documentos-e-impressao/ 3
https://www.spreadthesign.com/pt.br/search/by-category/235/tecnologia-de-video/ 3
https://www.spreadthesign.com/pt.br/search/by-category/236/tecnologia-de-audio/ 1
https://www.spreadthesign.com/pt.br/search/by-category/238/geral-tecnologia-moderna/ 1
https://www.spreadthesign.com/pt.br/search/by-category/228/tecnologia-de-computadores/ 7
https://www.spreadthesign.com/pt.br/search/by-category/234/comunicacao-telefones/ 1
https://www.spreadthesign.com/pt.br/search/by-category/233/documentos-e-impressao/ 3
https://www.spreadthesign.com/pt.br/search/by-category/235/tecnologia-de-video/ 3
https://www.spreadthesign.com/pt.br/search/by-category/236/tecnologia-de-audio/ 1
https://www.spreadthesign.com/pt.br/search/by-category/238/geral-tecnologia-moderna/ 1
https://www.spreadthesign.com/pt.br/search/by-category/168/ciencia/ 50
https://www.spreadthesign.com/pt.br/search/by-category/7/matematica/ 5
https://www.spreadthesign.com/pt.br/search/by-category/190/biologia/ 5
https://www.spreadthesign.com/pt.br/search/by-category/169/anatomia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/170/genetica/ 2
https://www.spreadthesign.com/pt.br/search/by-category/175/geral-animais/ 8
https://www.spreadthesign.com/pt.br/search/by-category/178/arvores-e-florestas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/179/botanica-e-jardinagem/ 7
https://www.spreadthesign.com/pt.br/search/by-category/184/geologia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/182/agua/ 2
https://www.spreadthesign.com/pt.br/search/by-category/185/tempo/ 2
https://www.spreadthesign.com/pt.br/search/by-category/183/natureza/ 2
https://www.spreadthesign.com/pt.br/search/by-category/187/sustentabilidade-e-vida-ecologica/ 1
https://www.spreadthesign.com/pt.br/search/by-category/181/agricultura/ 3
https://www.spreadthesign.com/pt.br/search/by-category/192/quimica/ 5
https://www.spreadthesign.com/pt.br/search/by-category/191/fisica/ 6
https://www.spreadthesign.com/pt.br/search/by-category/257/astronomia/ 2
https://www.spreadthesign.com/pt.br/search/by-category/193/experimentacao-e-equipamento/ 2
https://www.spreadthesign.com/pt.br/search/by-category/7/matematica/ 5
https://www.spreadthesign.com/pt.br/search/by-category/190/biologia/ 5
https://www.spreadthesign.com/pt.br/search/by-category/169/anatomia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/170/genetica/ 2
https://www.spreadthesign.com/pt.br/search/by-category/175/geral-animais/ 8
https://www.spreadthesign.com/pt.br/search/by-category/178/arvores-e-florestas/ 2
https://www.spreadthesign.com/pt.br/search/by-category/179/botanica-e-jardinagem/ 7
https://www.spreadthesign.com/pt.br/search/by-category/184/geologia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/182/agua/ 2
https://www.spreadthesign.com/pt.br/search/by-category/185/tempo/ 2
https://www.spreadthesign.com/pt.br/search/by-category/183/natureza/ 2
https://www.spreadthesign.com/pt.br/search/by-category/187/sustentabilidade-e-vida-ecologica/ 1
https://www.spreadthesign.com/pt.br/search/by-category/181/agricultura/ 3
https://www.spreadthesign.com/pt.br/search/by-category/192/quimica/ 5
https://www.spreadthesign.com/pt.br/search/by-category/191/fisica/ 6
https://www.spreadthesign.com/pt.br/search/by-category/257/astronomia/ 2
https://www.spreadthesign.com/pt.br/search/by-category/193/experimentacao-e-equipamento/ 2
https://www.spreadthesign.com/pt.br/search/by-category/194/saude-e-medicina/ 26
https://www.spreadthesign.com/pt.br/search/by-category/196/condicoes-medicas/ 13
https://www.spreadthesign.com/pt.br/search/by-category/202/profissionais-de-saude/ 2
https://www.spreadthesign.com/pt.br/search/by-category/203/saude-mental-e-dependencias/ 1
https://www.spreadthesign.com/pt.br/search/by-category/256/psicologia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/206/saude-dentaria/ 1
https://www.spreadthesign.com/pt.br/search/by-category/208/gravidez-e-reproducao/ 2
https://www.spreadthesign.com/pt.br/search/by-category/211/sexo-e-genero/ 2
https://www.spreadthesign.com/pt.br/search/by-category/212/geral-saude/ 5
https://www.spreadthesign.com/pt.br/search/by-category/196/condicoes-medicas/ 13
https://www.spreadthesign.com/pt.br/search/by-category/202/profissionais-de-saude/ 2
https://www.spreadthesign.com/pt.br/search/by-category/203/saude-mental-e-dependencias/ 1
https://www.spreadthesign.com/pt.br/search/by-category/256/psicologia/ 3
https://www.spreadthesign.com/pt.br/search/by-category/206/saude-dentaria/ 1
https://www.spreadthesign.com/pt.br/search/by-category/208/gravidez-e-reproducao/ 2
https://www.spreadthesign.com/pt.br/search/by-category/211/sexo-e-genero/ 2
https://www.spreadthesign.com/pt.br/search/by-category/212/geral-saude/ 5
https://www.spreadthesign.com/pt.br/search/by-category/255/sinais-do-bebe/ 5
https://www.spreadthesign.com/pt.br/search/by-category/406/especifico-do-pais/ 1
"""

linhas = texto.strip().split('\n')

dados = []
for linha in linhas:
    link, quantidade = linha.split()
    dados.append({'Link': link, 'Paginas': int(quantidade)})

df = pd.DataFrame(dados)
print(df)
# Para salvar em um arquivo CSV
df.to_csv('links_categorias_spreadthesign.csv', index=False)